Api tests
dinaigul/teamcity-testing-framework pull request #1
Opened 2024-10-08 20:23 UTC by dinaigul

2024-10-12 16:12 UTC, nobugs-me requested changes
Привет! 

Твои изменения в тесте не попали в Pull Request, сможешь добавить?

2024-10-12 16:12 UTC, nobugs-me commented on src/test/java/com/example/teamcity/api/BuildTypeTest.java
> -        //generating and creating user2 with project admin role
Не вижу изменений в тесте

2024-10-12 18:33 UTC, dinaigul commented on src/test/java/com/example/teamcity/api/BuildTypeTest.java
> -        //generating and creating user2 with project admin role
![image](https://github.com/user-attachments/assets/411b2e36-37fb-44bf-8fe8-9a7f81462fe9)
![image](https://github.com/user-attachments/assets/1fd54a17-d941-4d86-b856-8ed2e8271500)
все иземенения актуальны по идее. тебе не видны эти тесты?

2024-10-12 20:27 UTC, nobugs-me commented on src/test/java/com/example/teamcity/api/BuildTypeTest.java
> -        //generating and creating user2 with project admin role
Нужно добавить их в Pull Request - можно открыть и увидеть, что там их нет

2024-10-12 20:57 UTC, dinaigul commented on src/test/java/com/example/teamcity/api/BuildTypeTest.java
> -        //generating and creating user2 with project admin role
https://github.com/dinaigul/teamcity-testing-framework/pull/1/files зашла под другим юзером в гитхабе, все изменения видны. мб ты не по той линке смотришь? или проблема в кэше

2024-10-14 13:19 UTC, nobugs-me approved these changes
Привет! 

Спасибо за выполнение базового ДЗ! ⚡️

Тест выполнен корректно, поэтому ставлю Approve 🤝

2024-10-14 13:19 UTC, nobugs-me commented on src/test/java/com/example/teamcity/api/BuildTypeTest.java
> +                .body(Matchers.containsString("The build configuration / template ID \"%s\" is already used by another configuration or template".formatted(testData.getBuildType().getId())));
В будущем все одинаковые типы ассертов можно вынести в отдельный класс и добавлять набор ассертов как ResponseSpecification

2024-10-14 13:19 UTC, nobugs-me commented on src/test/java/com/example/teamcity/api/BuildTypeTest.java
> +        testData.getUser().setRoles(generate(Roles.class, "PROJECT_ADMIN", "p:" + testData.getProject().getId()));
"PROJECT_ADMIN" можно вынести в Enum

2024-10-28 09:32 UTC, merged