Added UI tests
dinaigul/teamcity-testing-framework pull request #2
Opened 2024-11-03 21:35 UTC by dinaigul

2024-11-10 22:25 UTC, nobugs-me requested changes
Привет! 

Спасибо за выполнение базового ДЗ! ⚡️

Тест выполнен корректно, но не хватает проверки, что сущность не создалась в негативном тесте. 

Добавь, пожалуйста, и будет Approve 🤝

2024-11-10 22:25 UTC, nobugs-me commented on src/test/java/com/example/teamcity/ui/CreateProjectTest.java
> +        var projectExists = ProjectsPage.open().getProjects().stream().anyMatch(project -> project.getName().text().equals(testData.getProject().getName()));
Отлично!

2024-11-10 22:25 UTC, nobugs-me commented on src/test/java/com/example/teamcity/ui/CreateBuildTypeTest.java
> +        ErrorElement.searchErrorValidationText("buildTypeName","Build configuration name must not be empty");
Отлично! Не хватает проверки на уровне API, что сущность не создалась.

2024-11-11 14:11 UTC, dinaigul commented on src/test/java/com/example/teamcity/ui/CreateBuildTypeTest.java
> +        ErrorElement.searchErrorValidationText("buildTypeName","Build configuration name must not be empty");
Добавила проверку https://github.com/dinaigul/teamcity-testing-framework/pull/2/commits/355fbd5cb956d1e35a90f62f8c43a25a3feaa622

2024-11-13 16:28 UTC, nobugs-me approved these changes

2024-11-13 18:10 UTC, merged